USE [master]
GO

/****** Object:  Database [Facturas]    Script Date: 18/09/2021 17:35:49 ******/
DROP DATABASE [Facturas]
GO

/****** Object:  Database [Facturas]    Script Date: 18/09/2021 17:35:49 ******/
CREATE DATABASE [Facturas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Facturas', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Facturas.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Facturas_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Facturas_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Facturas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Facturas] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Facturas] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Facturas] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Facturas] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Facturas] SET ARITHABORT OFF 
GO

ALTER DATABASE [Facturas] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Facturas] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Facturas] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Facturas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Facturas] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Facturas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Facturas] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Facturas] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Facturas] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Facturas] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Facturas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Facturas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Facturas] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Facturas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Facturas] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Facturas] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Facturas] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Facturas] SET RECOVERY FULL 
GO

ALTER DATABASE [Facturas] SET  MULTI_USER 
GO

ALTER DATABASE [Facturas] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Facturas] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Facturas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Facturas] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Facturas] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Facturas] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Facturas] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Facturas] SET  READ_WRITE 
GO


